language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

notifications:
  email: true

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'


script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew build connectedCheck
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)